### ISSUE TITLE
Add requeriments.txt and setup.py

### ISSUE THREAD

**Issue by mstuttgart** [vishichoudhary/mygist#14]
@vishichoudhary 
Can I add requeriments.txt and setup.py file with `mygist` project dependecies?

**Comment by vishichoudhary** [comment]
Yeah , Waiting for your pr

**Comment by mstuttgart** [comment]
Cool! Please, add `hacktoberfest` label. :+1: 
I will work in this.

**Comment by vishichoudhary** [comment]
Done, PR counts no matter they have hactoberfest label or not. :-)
